# Generated by Django 4.1.7 on 2023-03-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголоавок')),
                ('description', models.TextField(max_length=400, verbose_name='Короткий опис')),
                ('content', models.TextField(max_length=10000, verbose_name='Основний текст')),
                ('date', models.DateField(verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
