# Generated by Django 4.1.7 on 2023-05-27 17:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(max_length=400, verbose_name='Короткий опис')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='Основний текст')),
                ('image', models.ImageField(null=True, upload_to='image/%Y')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
