# Generated by Django 4.1.7 on 2023-06-29 18:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='image/theme/%Y')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Теми',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=200, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=400, verbose_name='Короткий опис')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='Основний текст')),
                ('image', models.ImageField(null=True, upload_to='image/%Y')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Теми', to='projects.theme')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
