# Generated by Django 4.1.7 on 2023-05-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(null=True, upload_to='image/theme/%Y'),
        ),
    ]
