# Generated by Django 4.1.7 on 2023-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_options_post_author_post_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_login', models.TextField(blank=True, help_text='Логін користувача', max_length=5000, null=True)),
                ('user_name', models.TextField(blank=True, help_text='Імя користувача', max_length=5000, null=True)),
                ('phone_number', models.DateTimeField(auto_now=True)),
                ('delivery_adress', models.TextField(blank=True, help_text='Адреса доставки', max_length=5000, null=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
