# Generated by Django 4.1.7 on 2023-04-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_city_remove_order_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Нова Погта'), ('delivery', 'Укрпошта')], default='self', max_length=40, verbose_name='Тип доставки'),
        ),
    ]
