# Generated by Django 4.1.7 on 2023-05-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_phone_order_postal_code_remove_order_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
