# Generated by Django 4.1.7 on 2023-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainUserExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=200)),
                ('work_company', models.TextField(blank=True, help_text='Назва компанії', max_length=100, null=True)),
                ('work_position', models.TextField(blank=True, help_text='Імя', max_length=100, null=True)),
                ('work_description', models.TextField(blank=True, help_text='Прізвище', max_length=100, null=True)),
                ('work_start', models.DateTimeField()),
                ('work_end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Досвід',
                'verbose_name_plural': 'Досвід роботи',
            },
        ),
        migrations.CreateModel(
            name='MainUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_login', models.TextField(blank=True, help_text='Логін користувача', max_length=100, null=True)),
                ('user_name', models.TextField(blank=True, help_text='Імя', max_length=100, null=True)),
                ('user_sur_name', models.TextField(blank=True, help_text='Прізвище', max_length=100, null=True)),
                ('user_birthday', models.TextField(blank=True, help_text='Прізвище', max_length=100, null=True)),
                ('user_email', models.TextField(blank=True, help_text='Електронна пошта', max_length=100, null=True)),
                ('user_phone', models.TextField(blank=True, help_text='Телефон', max_length=100, null=True)),
                ('user_site', models.TextField(blank=True, help_text='Сайт', max_length=100, null=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('user_subscribe', models.TextField(blank=True, help_text='Короткий опис', max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Основна інформація',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='MainUserSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=200)),
                ('skill_name', models.TextField(blank=True, help_text='Назва', max_length=100, null=True)),
                ('skill_count', models.TextField(blank=True, help_text='Рівень навику', max_length=100, null=True)),
                ('skill_status', models.TextField(blank=True, help_text='Статус', max_length=100, null=True)),
                ('skill_description', models.TextField(blank=True, help_text='Короткий опис', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Навички',
                'verbose_name_plural': 'Навички',
            },
        ),
    ]
