# Generated by Django 4.1.7 on 2023-05-27 17:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainUserInfo',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(help_text='Фото', upload_to='cv/photo')),
                ('user_login', models.CharField(blank=True, help_text='Логін користувача', max_length=50)),
                ('user_name', models.CharField(blank=True, help_text='Імя', max_length=30, null=True)),
                ('user_sur_name', models.CharField(blank=True, help_text='Прізвище', max_length=50, null=True)),
                ('user_birthday', models.DateTimeField(blank=True, help_text='Дата народження', null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.PositiveIntegerField(blank=True, help_text='Телефон', null=True)),
                ('user_site', models.TextField(blank=True, help_text='Сайт', max_length=100, null=True)),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('user_subscribe', ckeditor.fields.RichTextField(blank=True, help_text='Короткий опис', max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Основна інформація',
                'verbose_name_plural': 'Персона',
            },
        ),
        migrations.CreateModel(
            name='MainUserSocial',
            fields=[
                ('social_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link', models.URLField(blank=True, help_text='Посилання', max_length=50, null=True)),
                ('social_name', models.CharField(choices=[('fb', 'Фейсбук'), ('linkid', 'Лінкайді'), ('utube', 'Ютуб')], help_text='Назва', max_length=7)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.mainuserinfo')),
            ],
            options={
                'verbose_name': 'Соціальні медіа',
                'verbose_name_plural': 'Соціальні медіа',
            },
        ),
        migrations.CreateModel(
            name='MainUserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=4)),
                ('skill_name', models.TextField(blank=True, help_text='Назва', max_length=100, null=True)),
                ('skill_count', models.CharField(help_text='Рівень навику', max_length=4)),
                ('skill_status', models.CharField(choices=[('a', 'Вивчаю'), ('b', 'На паузі'), ('c', 'В планах')], help_text='Статус', max_length=1)),
                ('skill_description', models.TextField(blank=True, help_text='Короткий опис', max_length=1000, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.mainuserinfo')),
            ],
            options={
                'verbose_name': 'Навички',
                'verbose_name_plural': 'Навички',
            },
        ),
        migrations.CreateModel(
            name='MainUserExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_company', models.TextField(blank=True, help_text='Назва компанії', max_length=100, null=True)),
                ('work_position', models.TextField(blank=True, help_text='Імя', max_length=100, null=True)),
                ('work_description', models.TextField(blank=True, help_text='Прізвище', max_length=100, null=True)),
                ('work_start', models.DateField(blank=True)),
                ('work_end', models.DateField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.mainuserinfo')),
            ],
            options={
                'verbose_name': 'Досвід',
                'verbose_name_plural': 'Досвід роботи',
            },
        ),
    ]
