# Generated by Django 4.1.7 on 2023-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuserinfo',
            name='user_birthday',
            field=models.DateTimeField(blank=True, help_text='Дата народження', null=True),
        ),
        migrations.AlterField(
            model_name='mainuserinfo',
            name='user_login',
            field=models.TextField(blank=True, help_text='Логін користувача', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainuserinfo',
            name='user_name',
            field=models.TextField(blank=True, help_text='Імя', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mainuserinfo',
            name='user_sur_name',
            field=models.TextField(blank=True, help_text='Прізвище', max_length=50, null=True),
        ),
    ]
