# Generated by Django 4.1.7 on 2023-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_mainuserinfo_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuserinfo',
            name='user_phone',
            field=models.TextField(blank=True, help_text='Телефон', max_length=12, null=True),
        ),
    ]
