# Generated by Django 4.1.7 on 2023-03-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_mainuserinfo_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuserinfo',
            name='user_image',
            field=models.ImageField(default=1, help_text='Фото', upload_to='image/%Y'),
            preserve_default=False,
        ),
    ]
