# Generated by Django 4.1.7 on 2023-03-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_mainuserinfo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuserexp',
            name='work_id',
            field=models.CharField(max_length=4),
        ),
    ]
