# Generated by Django 4.1.7 on 2023-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_mainuserexp_work_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=4)),
                ('skill_name', models.TextField(blank=True, help_text='Назва', max_length=100, null=True)),
                ('skill_count', models.CharField(help_text='Рівень навику', max_length=4)),
                ('skill_status', models.TextField(blank=True, help_text='Статус', max_length=100, null=True)),
                ('skill_description', models.TextField(blank=True, help_text='Короткий опис', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Навички',
                'verbose_name_plural': 'Навички',
            },
        ),
        migrations.DeleteModel(
            name='MainUserSkills',
        ),
        migrations.AlterField(
            model_name='mainuserinfo',
            name='user_image',
            field=models.ImageField(help_text='Фото', upload_to='cv/photo'),
        ),
    ]
