# Generated by Django 4.1.7 on 2023-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_mainuserskill_skill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuserexp',
            name='work_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainuserexp',
            name='work_id',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='mainuserexp',
            name='work_start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainuserskill',
            name='skill_description',
            field=models.TextField(blank=True, help_text='Короткий опис', max_length=1000, null=True),
        ),
    ]
