# Generated by Django 4.1.7 on 2023-04-06 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_mainuserexp_work_end_alter_mainuserexp_work_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuserinfo',
            name='user_subscribe',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Короткий опис', max_length=5000, null=True),
        ),
    ]
