# Generated by Django 4.1.7 on 2023-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_alter_mainuserinfo_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuserexp',
            name='work_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainuserexp',
            name='work_start',
            field=models.DateField(blank=True),
        ),
    ]
