# Generated by Django 4.1.7 on 2023-04-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_alter_mainuserexp_work_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('social_id', models.ImageField(help_text='Фото', upload_to='cv/photo')),
                ('social_link', models.TextField(blank=True, help_text='Логін користувача', max_length=50, null=True)),
                ('social_icn', models.TextField(blank=True, help_text='Імя', max_length=30, null=True)),
                ('social_name', models.TextField(blank=True, help_text='Прізвище', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Соціальні медіа',
                'verbose_name_plural': 'Соціальні медіа',
            },
        ),
    ]
