# Generated by Django 4.1.7 on 2023-05-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_usersocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuserskill',
            name='user_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
